# Generated by Django 5.1.6 on 2026-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
